name: Firebase RTDB to Firestore Sync

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 5 minutes
  workflow_dispatch:

concurrency:
  group: "firebase-sync"
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./firebase-sync

      - name: Run sync script
        run: node index.js
        working-directory: ./firebase-sync
